// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // Getting Started
    {
      type: 'category',
      label: '1) Getting Started',
      items: [{ type: 'autogenerated', dirName: '1-getting-started' }],
    },

    // Editor Manual
    {
      type: 'category',
      label: '2) Editor Manual',
      items: [{ type: 'autogenerated', dirName: '2-editor' }],
    },

    // Engine Concepts
    {
      type: 'category',
      label: '3) Engine Concepts',
      items: [{ type: 'autogenerated', dirName: '3-engine-concepts' }],
    },

    // Scripting API (manteniendo la carpeta como está)
    {
      type: 'category',
      label: '4) Scripting API',
      items: [{ type: 'autogenerated', dirName: '4-scripting-api' }],
    },

    // Advanced
    {
      type: 'category',
      label: '5) Advanced',
      items: [{ type: 'autogenerated', dirName: '5-advanced' }],
    },
  ],
};

export default sidebars;
